//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EISProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adjustment_Global_Settings_Table
    {
        public int adjustment_id { get; set; }
        public string adjustment_type { get; set; }
        public Nullable<int> amount_percent { get; set; }
    }
}
