//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EISProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance_Global_Settings_Table
    {
        public int setting_time_id { get; set; }
        public string global_time_in_mandatory { get; set; }
        public string global_time_out_mandatory { get; set; }
        public Nullable<int> late_grace_time_period { get; set; }
    }
}
