//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EISProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cash_Advance_Table
    {
        public int id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public string employee_name { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> total_payment { get; set; }
        public Nullable<decimal> amount_payment_per_month { get; set; }
        public Nullable<int> month_length { get; set; }
        public Nullable<decimal> remaining_balance { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string log_by { get; set; }
        public string status { get; set; }
    
        public virtual Employee_Information_Table Employee_Information_Table { get; set; }
    }
}
