//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EISProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Positions_Table
    {
        public int position_id { get; set; }
        public string position { get; set; }
        public System.DateTime date_added { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> rate_per_hour { get; set; }
        public string log_by { get; set; }
    }
}
