//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EISProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Allowance_Table
    {
        public int allowance_id { get; set; }
        public string allowance_name { get; set; }
        public string description { get; set; }
        public Nullable<decimal> amount_per_month { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string log_by { get; set; }
    }
}
