//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EISProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees_Documents_Table
    {
        public int file_id { get; set; }
        public int employee_id { get; set; }
        public string filename { get; set; }
        public string filetype { get; set; }
        public string employee_name { get; set; }
        public Nullable<System.DateTime> date_uploaded { get; set; }
        public string file_size { get; set; }
        public string added_by { get; set; }
    
        public virtual Employee_Information_Table Employee_Information_Table { get; set; }
    }
}
