//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EISProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Attendance_Table
    {
        public int attendance_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public string employee_name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string time_in { get; set; }
        public string time_out { get; set; }
        public Nullable<int> working_hours { get; set; }
        public string attendance_status { get; set; }
        public Nullable<int> overtime_hours { get; set; }
        public Nullable<decimal> rate_earned { get; set; }
        public string day_type { get; set; }
    
        public virtual Employee_Information_Table Employee_Information_Table { get; set; }
    }
}
