//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EISProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Portal_Accounts_Table
    {
        public int employee_id { get; set; }
        public string password { get; set; }
        public string account_status { get; set; }
        public int portal_account_id { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
    
        public virtual Employee_Information_Table Employee_Information_Table { get; set; }
    }
}
