//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EISProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Information_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee_Information_Table()
        {
            this.Cash_Advance_Table = new HashSet<Cash_Advance_Table>();
            this.Employee_Attendance_Table = new HashSet<Employee_Attendance_Table>();
            this.Employee_Portal_Accounts_Table = new HashSet<Employee_Portal_Accounts_Table>();
            this.employee_leave_table = new HashSet<employee_leave_table>();
            this.Employees_Documents_Table = new HashSet<Employees_Documents_Table>();
            this.Payroll_Table = new HashSet<Payroll_Table>();
        }
    
        public int employee_id { get; set; }
        public string employee_work_id { get; set; }
        public string last_name { get; set; }
        public string given_name { get; set; }
        public string middle_name { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public int age { get; set; }
        public string gender { get; set; }
        public string nationality { get; set; }
        public string civil_status { get; set; }
        public string Religion { get; set; }
        public string current_address { get; set; }
        public string house_lot_block_number { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string brgy { get; set; }
        public string zip_code { get; set; }
        public string email_address { get; set; }
        public string phone_number { get; set; }
        public string contract { get; set; }
        public string job_title { get; set; }
        public Nullable<decimal> rate_per_hour { get; set; }
        public string telephone { get; set; }
        public string campus_assigned { get; set; }
        public string department_name { get; set; }
        public System.DateTime date_hired { get; set; }
        public string work_location { get; set; }
        public string philhealth_number { get; set; }
        public string SSS_number { get; set; }
        public string TIN_number { get; set; }
        public string profile_picture { get; set; }
        public string employee_status { get; set; }
        public string required_documents { get; set; }
        public string description_for_archiving { get; set; }
        public string suspension_lift_date { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public Nullable<int> email_received { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cash_Advance_Table> Cash_Advance_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Attendance_Table> Employee_Attendance_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Portal_Accounts_Table> Employee_Portal_Accounts_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_leave_table> employee_leave_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employees_Documents_Table> Employees_Documents_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payroll_Table> Payroll_Table { get; set; }
    }
}
