//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EISProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeeInformationSystemDataBaseEntities : DbContext
    {
        public EmployeeInformationSystemDataBaseEntities()
            : base("name=HumanResourceDatabaseEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adjustment_Global_Settings_Table> Adjustment_Global_Settings_Table { get; set; }
        public virtual DbSet<Attendance_Global_Settings_Table> Attendance_Global_Settings_Table { get; set; }
        public virtual DbSet<Cash_Advance_Table> Cash_Advance_Table { get; set; }
        public virtual DbSet<Deductions_Table> Deductions_Table { get; set; }
        public virtual DbSet<Department_Table> Department_Table { get; set; }
        public virtual DbSet<Employee_Allowance_Table> Employee_Allowance_Table { get; set; }
        public virtual DbSet<Employee_Attendance_Table> Employee_Attendance_Table { get; set; }
        public virtual DbSet<Employee_Information_Table> Employee_Information_Table { get; set; }
        public virtual DbSet<employee_leave_table> employee_leave_table { get; set; }
        public virtual DbSet<Employee_Portal_Accounts_Table> Employee_Portal_Accounts_Table { get; set; }
        public virtual DbSet<Employee_Positions_Table> Employee_Positions_Table { get; set; }
        public virtual DbSet<Employees_Documents_Table> Employees_Documents_Table { get; set; }
        public virtual DbSet<Holidays_Table> Holidays_Table { get; set; }
        public virtual DbSet<HRIS_Account_Table> HRIS_Account_Table { get; set; }
        public virtual DbSet<HRIS_System_Global_Settings__Table> HRIS_System_Global_Settings__Table { get; set; }
        public virtual DbSet<Leave_Type_Table> Leave_Type_Table { get; set; }
        public virtual DbSet<Log_History_Table> Log_History_Table { get; set; }
        public virtual DbSet<Payroll_Table> Payroll_Table { get; set; }
        public virtual DbSet<Penalty_Global_Settings_Table> Penalty_Global_Settings_Table { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
