//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EISProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRIS_Account_Table
    {
        public int hris_account_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string access_level { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string account_status { get; set; }
        public string profile_picture { get; set; }
    }
}
