//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EISProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave_Type_Table
    {
        public int leave_type_id { get; set; }
        public string description { get; set; }
        public string leave_type_name { get; set; }
        public Nullable<System.DateTime> leave_type_date_added { get; set; }
    }
}
