//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EISProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_History_Table
    {
        public int log_id { get; set; }
        public int employee_id { get; set; }
        public Nullable<System.DateTime> login_date { get; set; }
        public string login_time { get; set; }
        public System.DateTime logout_date { get; set; }
        public string logout_time { get; set; }
    
        public virtual Log_History_Table Log_History_Table1 { get; set; }
        public virtual Log_History_Table Log_History_Table2 { get; set; }
    }
}
