//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EISProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalty_Global_Settings_Table
    {
        public int penalty_id { get; set; }
        public string penalty_type { get; set; }
        public Nullable<decimal> penalty_amount { get; set; }
    }
}
